// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DreamAnalysisController from "./dream_analysis_controller"
application.register("dream-analysis", DreamAnalysisController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ToggleFormController from "./toggle_form_controller"
application.register("toggle-form", ToggleFormController)

import TogglePageController from "./toggle_page_controller"
application.register("toggle-page", TogglePageController)
